version: '3.9'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    env_file:
      - ../.env.prod
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:6
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../ssl:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  postgres_data:
